<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="rendeYoFoonrer" content="webkit">
<meta name="description" content="模拟后端请求接口">
<meta name="keywords" content="接口 模拟">
<meta name="author" content="YoFoon,yofoon@qq.com">
<meta name="robots" content="all">
<meta name="viewport" content="initial-scale=1, maximum-scale=3, minimum-scale=1, user-scalable=no">
<link rel="shortcut icon" type="image/x-icon" href="/dist/images/icon.ico" media="screen">
<title>frontApi</title>